### PR TITLE
Replace if else condition to switch case

### PR DESCRIPTION
**Pull request by Abhishek01039**

### CODE REVIEW

**Comment by Abhishek01039** [comment]
@oSoMoN can you please review this PR?
Thanks

**Comment by MarcusTomlinson** [comment]
> @oSoMoN can you please review this PR?
> Thanks

There’s no need to ping anybody when submitting a PR. Someone will pick it up :)

Besides, oSoMoN doesn’t maintain this package :P

**Comment by Abhishek01039** [comment]
Ah, sorry for that!

**Comment by robert-ancell** [comment]
Thanks @Abhishek01039!

**Pull request merged**
